# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\attendance.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainwinow(object):
    def setupUi(self, mainwinow):
        mainwinow.setObjectName("mainwinow")
        mainwinow.setEnabled(True)
        mainwinow.resize(569, 247)
        mainwinow.setMaximumSize(QtCore.QSize(569, 247))
        self.filepath = QtWidgets.QLineEdit(mainwinow)
        self.filepath.setGeometry(QtCore.QRect(90, 111, 360, 25))
        self.filepath.setObjectName("filepath")
        self.startbutton = QtWidgets.QCommandLinkButton(mainwinow)
        self.startbutton.setGeometry(QtCore.QRect(214, 161, 115, 43))
        self.startbutton.setObjectName("startbutton")
        self.inputbutton = QtWidgets.QPushButton(mainwinow)
        self.inputbutton.setGeometry(QtCore.QRect(464, 111, 70, 25))
        self.inputbutton.setObjectName("inputbutton")
        self.label = QtWidgets.QLabel(mainwinow)
        self.label.setGeometry(QtCore.QRect(90, 26, 361, 54))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(mainwinow)
        self.label_2.setGeometry(QtCore.QRect(90, 90, 120, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(mainwinow)
        self.inputbutton.clicked.connect(mainwinow.openfile)
        self.startbutton.clicked.connect(mainwinow.startprocess)
        QtCore.QMetaObject.connectSlotsByName(mainwinow)

    def retranslateUi(self, mainwinow):
        _translate = QtCore.QCoreApplication.translate
        mainwinow.setWindowTitle(_translate("mainwinow", "考勤处理工具1.0"))
        self.startbutton.setText(_translate("mainwinow", "开始处理"))
        self.inputbutton.setText(_translate("mainwinow", "导入"))
        self.label.setText(_translate("mainwinow", "考勤处理工具"))
        self.label_2.setText(_translate("mainwinow", "选择原始考勤数据："))
